genometools/genometools

testdata/gt.supp

I cannot find a way to control these allocations in GObject and Glib, which are done even without doing any drawing. So for now I'm adding suppressions for these fairly small leaks to not clutter Valgrind output.
Closes #521.

add suppressions for GObject/Glib/pixman 'leaks'

---

src/core/assert_api.h

Remind the user to run the latest release. Hopefully this will reduce the number
of false bug reports.
New message:
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.

make assert message more verbose

---

src/extended/gff3_linesorted_out_stream.c

This PR fixes a bug in the GtGFF3LinesortedOutStream class. This bug would sometimes cause the sorting to  be incorrect for seqids with different lengths, i.e. to have lines appear out of order, leading to problems with downstream processors such as Tabix.

fix seqid comparison in line sorting outstream

---

src/extended/type_graph.c
src/extended/type_node.c
src/extended/type_node.h
testdata/transient_edges_bug.gff3
testsuite/gt_gff3validator_include.rb

The transient part_of edges have to be created for the parent in a "has parent"
check (and not for the child). In earlier versions they have been created for
the child and this worked for the standard gene example, because in that case
the mRNA parent was a gene child before. In added test file that is not the case
and therefore it failed erroneously.
This commit also documents how the transient edges are created in more detail.
Resolves #514

bug fix: create transient edges for parent

---

src/extended/genome_node_api.h
src/extended/gff3_parser.c
src/extended/gff3_visitor.c
src/extended/meta_node.c
src/extended/meta_node_api.h
testdata/unknown_meta_directive_without_argument.gff3
testsuite/gt_gff3_include.rb
www/genometools.org/htdocs/docs.html
www/genometools.org/htdocs/libgenometools.html
www/genometools.org/htdocs/tools.html
www/genometools.org/htdocs/tools/gt_convertseq.html
www/genometools.org/htdocs/tools/gt_encseq_encode.html

Until now an unknown-meta directive had to have data. Make the parser more
forgiving.

gff3 parser: allow unknown pragmas without data

---

gtpython/tests/test_metanode.py
src/extended/meta_node.c
src/gtlua/genome_node_lua.c
testdata/gtscripts/genome_node.lua

#531 allowed meta data from GFF3 pragmas to be empty, with the API functions returning NULL in this case. This PR adapts the GenomeTools bindings to support this by returning `nil` (Lua) or 'None' (Python)  instead of expecting a proper string to be returned at all times.

support empty meta data in bindings

---

src/extended/hmm.c
src/ltr/ltrdigest_ppt_visitor.c

13f80cf556aaa96578a0ab9ba0220a11712b5253 introduced a bug leading to wrong Viterbi decoded states, which in turn results in missing predicted polypurine tracts in LTRdigest. This PR fixes this issue. 
Thanks to Yanzhu Ji for reporting the issue on the gt-users mailing list.

Fix bug in HMM class

---

Makefile

This PR allows building of a fully working GenomeTools version after installing the dependencies via Homebrew (`cairo`,`pango`). Without these modifications an image created by AnnotationSketch is empty (just a white plane).

fix manual building on Mac OS X with cairo deps from Homebrew

---

src/core/bioseq.c

This PR addresses #560, where an incorrect GC content is reported on Windows. This is due to sequences being extracted into an unterminated buffer, which eventually was read beyond the actual sequence, changing the results of the GC content calculation.

fix GtBioseq sequence extraction

---

Brewfile
INSTALL

Using Brewdler (https://github.com/Homebrew/homebrew-brewdler) it is possible to quickly specify a set of dependencies to be installed from the Homebrew repos, in the style of Bundler. This PR adds a Brewfile containing the necessary dependencies to compile GenomeTools on OS X.
(This is basically up for discussion, so if no one else sees value in this, we need not merge this. It is quite specific.)

Add Brewfile for easier Homebrew dependency installation

---

src/core/fileutils.c

I'm trying to install genometools using linuxbrew, and it was complaining about not finding the `/gtdata` directory. This was because the `gt` binary was being symlinked into a directory on `PATH`, and thus the `/gtdata` directory wouldn't exist going up a single parent directory. 
In this change, the absolute path of `gt` is detected before looking around it. This has the drawback if the `bin` dir is symlinked and a `/gtdata` dir is placed up next to it, which I think is a less likely use case.
Also doesn't handle windows but just want to discuss this.

Absolute path resolve for exec in bindir (for gtdata directory).

---

Makefile

Apparently OS X 10.10 includes a new compiler version which introduces a check for extra parentheses around equality checks. These are used in numerous places in the gt code, including macros, causing the build to fail with `-Werror`. Disabling this in the Makefile since I consider these a bit too restrictive.

allow compiling on OSX Yosemite

---

src/extended/match_iterator_blast.c

I have received a bug report from a LTRsift user running into a failing assertion:
```
Assertion failed: (call->nucl), function gt_blast_process_call_set_penalty, file src/extended/blast_process_call.c, line 191.
This is a bug, please report it at https://github.com/genometools/genometools/issues.
```
while trying to align a reference sequence set to some LTR retrotransposon candidates in LTRsift. It seems to me that there might be a problematic constructor in the reworked API, creating a protein BLAST call where a nucleotide one is expected.
This PR addresses this issue.

use correct GtBlastProcessCall constructor

---

Makefile
src/external/lpeg-0.10.2/lpeg.c
src/external/lua-5.1.5/src/lapi.c
src/external/lua-5.1.5/src/ldebug.c
src/external/lua-5.1.5/src/ldo.c
src/external/lua-5.1.5/src/lobject.h
src/external/lua-5.1.5/src/ltable.c
src/external/lua-5.1.5/src/luaconf.h
src/external/lua-5.1.5/src/lvm.c
src/external/tre/lib/tre-ast.h
src/external/tre/lib/tre-compile.c
src/match/merger-trie.c
src/match/sfx-bentsedg.c

addresses concerns raised in #570

adjust use of parentheses around comparisons in macros

---

src/core/bioseq_col.c
src/core/encseq_col.c
src/core/seq_col.c
src/core/seq_col.h
src/core/seq_col_rep.h
src/extended/region_mapping.c
src/extended/seqid2seqnum_mapping.c

In http://genometools.org/pipermail/gt-users/2015-April/000775.html a problem was reported with LTRdigest and its output options. Sequence IDs were missing from the headers of the written FASTA files. Apparently the case in which a sequence description is queried from a GtSeqCol using `-usedesc` or `-matchdesc` and no MD5 information is present to process this query had not been implemented in the GtRegionMapping class.
This PR addresses this issue.

fix issues with seqid mappings

---

src/tools/gt_gff3.c
testsuite/gt_gff3_include.rb

Allows to just use `-sort` or `-sortlines` without having to also give `-sort`. See #581.

make -sort implicit

---

src/tools/gt_gff3.c
testdata/gff3_numeric_a.gff
testsuite/gt_gff3_include.rb

Addresses the issue raised in #581. Note that the problem described does not occur when using `-sort sortnum` instead of `-sortnum` which implied that some additional region joining step performed in the former case did not take place in the latter.
This PR fixes the issue and adds the minimal example provided by the reporter as a test case.

fix issues with implicit `-sort`

---

src/extended/extract_feature_sequence.c
src/extended/extract_feature_sequence.h
src/extended/extract_feature_visitor.c
src/gtlua/genome_node_lua.c

This PR fixes a bug in `gt extractfeat` where the `-translate` option would not work with either the `-seqid` or `-target` options (or both).
Closes #593.

extractfeat: support `-seqid` and `-target` together with `-translate`

---

src/extended/extract_feature_stream.c
src/extended/extract_feature_stream_api.h
src/extended/extract_feature_visitor.c
src/extended/extract_feature_visitor.h
src/tools/gt_extractfeat.c

Addresses #597. Coordinates are added to the `-seqid` output if the `-coords` option is given in addition.

add coordinates output for extractfeat tool

---

src/extended/tir_stream.c

fixes a bug where an assertion would fail when a seed is to be extended
to the left one character away from the beginning of a sequence

fix bug in TIRvish

---

src/ltr/ltrharvest_stream.c

If, for instance, LTRharvest users is re-using an ESA built for TIRvish (which needs to be mirrored), they will get the results twice! TIRvish has a check to ensure that the input index is mirrored; this introduces a similar check for LTRharvest, printing a warning when given a mirrored index.

add mirror check to LTRharvest tool

---

src/core/string_distri.h
src/extended/stat_visitor.c
src/tools/gt_stat.c
testdata/gt_stat_cdslengthdistri.out
testdata/gt_stat_exonnumberdistri_standard.out
testdata/gt_stat_source.out
testdata/gt_stat_test_1.out
testdata/gt_stat_test_2.out
testdata/gt_stat_test_3.out
testdata/gt_stat_test_4.out
testdata/gt_stat_test_5.out
testdata/gt_stat_test_6.out

This PR adds occurrence counting for any kind of feature type encountered by the GtStatVisitor, instead of only selected hard-coded ones. These are of course still supported, but any other type and its count is reported as well. Example:
```
[ss34@mib106184i:~/develop/genometools] gt stat Lmajor.gff3
parsed genome node DAGs: 17890
sequence regions: 36 (total length: 32841480)
genes: 9284
protein-coding genes: 9284
mRNAs: 8307
protein-coding mRNAs: 8307
CDSs: 9288
ncRNAs: 84
polypeptides: 8400
pseudogenes: 93
pseudogenic_exons: 175
pseudogenic_transcripts: 93
rRNAs: 63
repeat_units: 3
snRNAs: 6
snoRNAs: 741
tRNAs: 83
```
NOTE: This obviously changes the output of `gt stat` - any comments on whether this is OK?
Closes #624.

add generic type counts to 'gt stat' output 

---

src/extended/merge_stream.c
testsuite/gt_merge_include.rb

This PR fixes #626 in which an assertion is triggered if an unsorted GFF file (other than the first) is input. This fix resolves this issue by correctly printing an error message.

Fix sortedness issue in `gt merge`

---

src/external/lua-5.1.5/src/luaconf.h

This fixes a minor issue with GCC 5:
```
In file included from /home/vagrant/genometools/src/external/lua-5.1.5/src/lua.h:16:0,
from /home/vagrant/genometools/src/external/lua-5.1.5/src/lapi.c:16,
from src/lualib.c:7:
/home/vagrant/genometools/src/external/lua-5.1.5/src/lcode.c: In function ‘constfolding’:
/home/vagrant/genometools/src/external/lua-5.1.5/src/luaconf.h:540:29: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
#define luai_numeq(a,b)  (a)==(b)
^
/home/vagrant/genometools/src/external/lua-5.1.5/src/luaconf.h:543:28: note: in expansion of macro ‘luai_numeq’
#define luai_numisnan(a) (!luai_numeq((a), (a)))
^
/home/vagrant/genometools/src/external/lua-5.1.5/src/lcode.c:647:7: note: in expansion of macro ‘luai_numisnan’
if …
```

allow compiling with GCC 5

---

src/extended/tag_value_map.c

Addresses the problem in #659. The terminal value in a GtTagValueMap was also found as a tag with empty value.

fix problem with GtTagValueMap

---

src/extended/tag_value_map.c

This fix will skip values when searching for tags in GtTagValueMaps, otherwise values would be found as tags. That is, if there are pairs such as:
```
tag1 -> value1,
tag2 -> value2,
tag3 -> value3
```
then querying for `value2` as a tag returned `tag3` as the value! Now the pairs are considered while searching, making sure this does not happen.
This still touches #659 and should now fix this issue for good.

make sure tag-value maps are searched in pairs

---

src/ltr/gt_ltrdigest.c
src/ltr/ltrdigest_file_out_stream.c
testsuite/gt_ltrdigest_include.rb

This PR fixes a failed assertion in LTRdigest triggered when the location given with `-outfileprefix` is not valid, i.e. in a non-existent or non-writable directory.

fix error reporting in LTRdigest

---

testsuite/gt_cds_include.rb
testsuite/gt_condenseq_include.rb
testsuite/gt_extractfeat_include.rb
testsuite/gt_extractseq_include.rb
testsuite/gt_fingerprint_include.rb
testsuite/gt_idxsearch_include.rb
testsuite/gt_kmer_database_include.rb
testsuite/gt_ltrdigest_include.rb
testsuite/gt_md5_to_id_include.rb
testsuite/gt_mgth_include.rb
testsuite/gt_scripts_include.rb
testsuite/gt_seq_include.rb
testsuite/gt_splicesiteinfo_include.rb
testsuite/gt_splitfasta_include.rb

**Issue**: *make test* produces several index files in testdata and gttestdata (sub-)directories. 
When threaded tests produce the same files simultaneously, there can occur write conflicts. 
[testdata_modifications.txt](https://github.com/genometools/genometools/files/5113/testdata_modifications.txt)
**Solution**: Intermediate files are created only in the test's working directory.

clean (gt)testdata

---

src/core/spacecalc.h

As @stefan-kurtz pointed out, I can't recollect why the strange divisors (minus one) were used to convert space values to KB/MB/GB. Making these more straightforward.

adjust spacecalc macros

---

src/extended/diagonalbandalign_affinegapcost.c
src/extended/linearalign_affinegapcost.c

fix warning from i686-apple-darwin10-gcc-4.2.1

initialize variables

---

src/tools/gt_speck.c

This PR allows a user of the `gt speck` tool to provide a template for output rendering as a full path to a file instead of referring to one in `gtdata/speck/output_drivers`. This makes it easier to use project-specific output formats without having to mess with the global `gtdata` directory.

allow speck templates to be given as files

---

src/tools/gt_speck.c

This PR makes sure that coloured output is disabled when redirecting or piping speck output.

clean up speck output on redirection

---

testsuite/gt_gff3_include.rb

This PR adjusts the large (gttestdata enabled) tests in `gt_gff3_include.rb` to not require the file `gttestdata/gff3/Drosophila_melanogaster.BDGP5.4.50.gff3.sorted` any more as it is identical to its non-sorted counterpart.

do not require duplicated gttestdata file

---

Makefile

This PR makes sure that any file lists produced in the main GenomeTools Makefile are returned in sorted order. Otherwise the `$(wildcard ...)` make function will return the filenames in arbitrary order, which may influence build results.

compile files in deterministic order

---

src/core/cstr_api.h
src/core/radix_sort.c
src/match/eis-bwtseq.h
src/match/eis-encidxseq.h
src/match/eis-voiditf.h
src/tools/gt_condenseq_compress.c
www/genometools.org/htdocs/libgenometools.html

This PR changes the misspelled word 'occurence' to 'occurrence'. Debian's lintian complains about this.

spelling fix: occurence -> occurrence

---

src/core/sequence_buffer_embl.c
src/core/sequence_buffer_gb.c
testdata/embl_test5.fas
testdata/genbank_test2.fas
testdata/shorten_desc.clipped.fas
testdata/shorten_desc.embl
testdata/shorten_desc.fas

This PR makes the EMBL and GenBank parsers recognize `ID` and `LOCUS` lines,  like they would be needed if there is no `DE`scription. The IDs will be the first part of the parsed header, and the description will be concatenated to it, with a space in between.

Parse ID/LOCUS lines in EMBL/GenBank sequence input

---

scripts/all-vs-all.sh
src/core/mathsupport.c
src/extended/multieoplist.c
src/external/zlib-1.2.8/inflate.c
src/match/querymatch-align.c
src/match/querymatch-align.h
src/match/querymatch.c
src/match/querymatch.h
src/match/seed-extend-iter.c
src/match/seed-extend-iter.h
src/tools/gt_repfind.c
src/tools/gt_seed_extend.c
src/tools/gt_show_seedext.c

- show_seedext can store the matches internally to sort them. After the sorting the  _next method
can be used as before, but enumerating the matches in sorted order.
- the last commit concerns some fixed to allow compilation with clang 3.7.0 on Linux.
Please check the applied modification in the zlib.

Sk Add sorting option for gt dev show_seedext

---

src/extended/condenseq.c

This reverts commit 045d6f204465dc16dee1c8a71650deab9bcdcf33.
This commit was done without a pull request and should be discussed as the
assumption to remove the assertion without replacing it by a warning or an
GtError is simply wrong.

Revert "Remove assertion. Bugfix."

---

src/ltr/ltrdigest_file_out_stream.c
testsuite/gt_ltrdigest_include.rb

This PR fixes a bug in LTRdigest where not all feature sequences would be included in the per-domain output files. Addresses second issue reported in #662.

Fix writing of LTRdigest output files

---

testsuite/testsuite.rb

Avoid the use of 'which' to determine whether python is available.
'which' is not guaranteed to be available, so a ruby-only equivalent
is more robust.

testsuite: avoid the use of 'which'

---

testsuite/testsuite.rb

This commit allows to run test scripts without assuming that environment var. PATH is set.

Check hash for whether it has key PATH

---

Makefile

Otherwise the GenomeThreader build breaks.

add missing GT_CFLAGS to TRE compilation rule

---

gtdata/spec/output_drivers/tabular
src/tools/gt_speck.c

This PR adds a new output format to `gt speck`: a simple tab-separated text format suitable for loading into Excel and friends, making it easier to prepare lists of issues without having to parse them manually from one of the other, more structured formats.

add tabular speck output template

---

doc/manuals/annotationsketch.tex
doc/manuals/genomediff.tex
doc/manuals/hop.tex
doc/manuals/ltrdigest.tex
doc/manuals/ltrharvest.tex
doc/manuals/mgth.tex
doc/manuals/packedindex.tex
doc/manuals/readjoiner.tex
doc/manuals/repfind.tex
doc/manuals/tagerator.tex
doc/manuals/tallymer.tex
doc/manuals/uniquesub.tex

IMHO manuals should have a specific date, and the date they were built should not be meaningful there. This commit initialises the date fields in the manuals by setting the date to the last modification date of the file in git, as given by:
```
for f in doc/manuals/*.tex; do
export OUT=`TZ=UTC LC_ALL=C date -d "$(git log -1 --format='%aD' -- $f )" +'%d\/%m\/%Y'`;
sed -ri "s/.begin.document./\\\date{$OUT}\n\\\begin{document}/g" $f;
unset OUT;
done
```
OK with everyone?

introduce dates for manuals

---

scripts/gen-randseq.rb

Ruby < 1.9.2 does not have a `Random` class in its standard library. This breaks the `gt repfind` tests, which use `scripts/gen-randseq.rb`, requiring this class.
This PR adds a compatible version of `scripts/gen-randseq.rb`, adding a minimal implementation of this class if it's not present. This might fix some intermittent test failures on Travis and also improves compatibility with older Ruby setups.

implement Ruby <1.9.2 version of gen-randseq.rb

---

Makefile
src/external/lpeg-0.10.2/lpeg.c
src/external/lua-5.1.5/src/lobject.h
src/external/lua-5.1.5/src/lua.h

This fixes/silences a couple of compiler warnings in the Lua 5.1 source, appearing in Apple's latest shipped clang. These broke the build with `-Werror` on latest OS X.
Not sure how `-Wno-parentheses-equality` behaves in other or older compilers.  According to https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html this should at least not concern GCC.
If merged this closes #776.

fix Clang's compiler warnings

---

src/core/bioseq.c

This reverts commit c4b5870965270ac3ffb12379c19c2b8bdce54935.
See #791

Revert "use basename as indexname for encoded seq in bioseq"

---

gtpython/tests/test_version.py

This removes the dependency on `assertIsNotNone()` which was only added in Python 2.7 and causes tests to fail on Python 2.6. Closes #795.

make unit tests compatible with Python 2.6

---

gtdata/spec/speclib.lua

This PR introduces more natural sounding wording for the speck matchers. That is, instead of
```
expect(foo).should_be(bar);
```
you can now additionally use
```
expect(foo).to_be(bar);
```
For negative assertions, multiple variants are recognized, i.e.:
```
expect(foo).should_not_contain(bar);
```
can also be written as:
```
expect(foo).to_not_contain(bar);
```
or even
```
expect(foo).not_to_contain(bar);
```

extend wording options for speck matchers

---

src/gtlua/region_mapping_lua.c
src/gtlua/region_mapping_lua.h

This PR addresses #804 by implementing the GtRegionMapping API, allowing to access sequences by their seqid to pull out sequences as strings, sequence lengths, descriptions (headers) and fingerprints.

add GtRegionMapping to Lua bindings

---

src/extended/spec_results.c
src/extended/spec_results.h
src/tools/gt_speck.c

- return non-zero status code when a run resulted in a runtime error or failed check 
Closes #811.

return non-zero status code on error or failure

---

src/tools/gt_readjoiner_assembly.c

- check for errors in assertion -- this might fix a case where the error code in a function that can fail at runtime is not checked before checking an invariant on the results 
Adresses #806.

skip assertion if had_err is set

---

src/core/encseq.c

- Adds support for mirrored sequences to `gt_encseq_contains_special()` used in Tallymer. 
Closes #816.

add support for mirrored sequences to gt_encseq_contains_special()

---

src/core/encseq.c
src/external/lua-5.1.5/src/ltablib.c
src/interactive.c

- Address warnings introduced by some new static checks in GCC 6 that cause builds to fail due to
`-Werror`. In this case, the warnings are complaining about potentially misleading indentation.
GCC6 is expected to be the default compiler in Debian stretch and also other Debian-derived distros so we better fix this asap.

allow compiling with GCC 6

---

gtdata/modules/gtdoclib/docvisitorlatex.lua
www/genometools.org/htdocs/docs.html
www/genometools.org/htdocs/libgenometools.html
www/genometools.org/htdocs/tools/gt_seed_extend.html

- Only use the location of `_` in a function name to align parameters if it exists. Currently this would break for `GtTrackSelectorFunc` which is handled like a function name while it is a function pointer type. 
- Update documentation prior to release
Fixes #821.

Fix documentation building

---

src/extended/condenseq_creator.c
src/extended/wtree_encseq.c
src/match/seqabstract.h
src/match/sfx-diffcov.c
src/tools/gt_show_seedext.c

- Fix spelling of 'position' in various non-API function names and comments.

spelling: positon -> position

---

src/extended/gff3_parser.c

- Improve robustness of GFF3 parser. If multi-features differ in attributes but one of these features misses the attribute completely, a segfault will occur due to unchecked `strcmp()` on the null pointer returned by `gt_feature_node_get_attribute()`.
Fixes #825.

make GFF3 multi-feature attribute comparison more robust

---

.travis.yml
scripts/travis_installdeps.sh

- Compilation tests for Mac OS X are added
- Travis dependency installation made more flexible to support Homebrew and apt
- Full test suite only run for a subset of make parameters
Adresses #830 by reorganising the test suite.

add OSX tests and slim down test permutations

---

.travis.yml
scripts/travis_installdeps.sh

- Do not run Homebrew's `brew` as root as it breaks Travis runs.

travis: do not run brew as root

---

src/extended/gff3_escaping.c
src/match/eis-bwtseq-context.c
src/match/gfa_writer.c

This PR introduces the following changes to allow proper building on GCC7 with `-Werror`:
- Adjust buffer sizes to allow for variable length `sprintf` output.
- Address compiler complaints regarding functions not returning a value.
Error message from before (example):
```
src/match/eis-bwtseq-context.c: In function ‘gt_BWTSCRFGet’:
src/match/eis-bwtseq-context.c:291:35: error: ‘cxm’ directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
^~~~~~~~
In file included from /usr/include/stdio.h:938:0,
from src/match/eis-bwtseq-context.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 6 and 10 bytes into a …
```

Fix building on GCC7

---

src/annotationsketch/custom_track_gc_content.c

escape '%' with '%%' instead of '\%'

---

src/extended/match_iterator_blast.c

Closes #864.
- Fix memleak when encountering an error during GtMatchIterator creation.
Fixes #864.

fix memory leak with nonexistent input file

---

src/match/diagbandseed.c

tvalBefore was flagged as garbage in line 2162 by clangs scan-build

scan-build garbage-value

---

Makefile
src/core/gtdatapath.c

- Install gtdata in `$PREFIX/share/genometools` by default.
- Extend search paths to account for relative gtdata location.
This addresses #618 which encourages the installation of gtdata outside `$PREFIX/bin` by default, which would also take some work away from packagers. There are also some adjustments to the relative search paths when trying to resolve the gtdata path to allow for arbitrary prefixes without having to compile them in.

install gtdata into $PREFIX/share/genometools

---

src/extended/assembly_stats_calculator.c
src/extended/assembly_stats_calculator.h
src/tools/gt_seqstat.c

- Add new option `-nstats` to `gt seqstat`. This options allows to specify a set of up to 10 N values between 0 and 100, which will then be calculated and output instead of just N50 and N80. These two are still the defaults though.
Please review carefully as I am not the main author of the modified code. Otherwise feel free to fix and contribute.
Example:
```
$ ./bin/gt seqstat -contigs -nstats 20 25 70 -- ./testdata/U89959_ests.fas
```
Adresses #850 by allowing arbitrary N values.

implement seqstat for arbitrary N values

---

scripts/travis_installdeps.sh

- Fix CI builds using Homebrew dependencies by no longer referencing the discontinued `homebrew/science` tap.

Fix CI builds using Homebrew

---

src/match/rdj-spmproc.c
src/match/rdj-spmproc.h
src/match/rdj-strgraph.c
src/tools/gt_readjoiner_asqg.c
src/tools/gt_readjoiner_assembly.c
src/tools/gt_readjoiner_gfa.c

scan-build complained about unitialized value in struct.
this PR initialises the value.
@ggonnella should check if this struct member is even needed anymore. As it seems to me it is unused.

initialize value

---

src/ltr/ltr_cluster_prepare_seq_visitor.c

- Make sure that the correct range is extracted for clustering in `gt ltrclustering` and LTRsift.
Fixes #858.

fix off-by-one error

---

.travis.yml
scripts/travis_installdeps.sh
src/ltr/ltr_cluster_prepare_seq_visitor.c
src/ltr/ltr_cluster_stream.c
src/match/eis-bwtseq-context.c

- Use larger buffer sizes to make sure that formatted strings _always_ fit into them.
This addresses some build errors caused by stricter static checking in newer compilers.
- Adjust environment variables in Travis macOS runs. (cf. https://github.com/Homebrew/homebrew-core/issues/40179 and https://github.com/gtk-rs/cairo/pull/264)
Fixes and closes #915 and #916.

use safer buffer sizes

---

src/match/sfx-opt.c
testsuite/gt_suffixerator_include.rb

- Disallow use of the `-j n` and `-lcp` switches in `gt suffixerator` when _n_ > 1. This is a result of an incomplete implementation of the experimental multithreaded ESA generation.
Fixes #922.

disallow LCP table generation when using >1 threads

---

src/ltr/ltr_cluster_prepare_seq_visitor.c
src/ltr/ltr_cluster_stream.c

- Ensure that error message is printed when an incompatible seqid format is given to `gt ltrdigest`. Previously it would just abort with a failed assertion.
Adresses #925 by providing a more informative error message.

fix error handling in case of invalid seqid

---

src/ltr/ltrdigest_strand_assign_visitor.c

- Do not raise an error when LTRdigest strand assignment notices disagreement between inout strands and determined strands, simply output a warning and propagate the determined strand
Adresses #927 by replacing a hard error with a warning when given output _not_ from _LTRharvest_ (which was expected before).

only warn about conflicting strands

---

Makefile
src/external/samtools-0.1.18/knetfile.c

These patches allow GenomTools to be compiled on OpenBSD (with `sharedlib=no`).
AnnotationSketch can be included if `cairo` and `pango` are installed.

make GenomeTools compile on OpenBSD

---

src/core/tooldriver.c
src/core/tooldriver_api.h
www/genometools.org/htdocs/docs.html
www/genometools.org/htdocs/libgenometools.html
www/genometools.org/htdocs/tools/gt_encseq_encode.html

This was probably never used outside of Vmatch/GenomeThreader and is not
necessary anymore.

remove unused license manager code

---

src/core/thread.c
src/ltr/ltrdigest_pdom_visitor.c

We noticed that the current implementation of passing data to and receiving data from HMMER's `hmmscan` in the `GtLTRdigestPdomVisitor` relies on the pipe buffer to store input and output while a single thread is handling writing and reading sequentially. This obviously causes problems once the buffer size is exceeded, with one side of the communication waiting for the other to read the flushed buffer contents.
This resulted in #970. I was able to process the data from #970 with no problem after this change.
Note that for this to work, GenomeTools needs to be built with `threads=yes`.
- Use separate threads for the read and write sides of the `hmmscan` communication.
Fixes #970.

use concurrent communication with hmmscan

---

Makefile

I would like to start a discussion about making `threads=yes` the default. With #971 I have added a way of doing things that will not work properly without pthread support, and I think it's time to finally expect this on target systems. Any objections?
- Change `Makefile` to treat `threads` as always enabled unless explicitly disabled.
Blocks #971

enable pthreads by default

---

gtpython/gt/extended/feature_node.py
gtpython/tests/__init__.py
gtpython/tests/test_featurenode.py

- Add `feature_node.remove_leaf()`.
- Fix pytest test invocation for Python 3.
- Add tests.
Adresses #969 by adding a missing Python API function.

Implement leaf deletion for gtpython API

---

src/ltr/ltrdigest_pdom_visitor.c

This PR fixes a bug where long `TMPDIR` values can lead to excessively long lines in the `hmmscan` output (which contains the full path to the temporary HMM files in the `TMPDIR`). These lines can exceed the buffer size for parsing outputs and cause the parsing of the whole output to fail.
This patch makes sure that long lines in the output also fit into the buffer to be made available for parsing. 
Thanks to E. Aunin for bringing this to my attention.
- Extend buffer size for `hmmscan` output parsing to 64K.
Probably related and fixing #662.

extend buffer for hmmscan output parsing

---

src/extended/gff3_parser.c

- Ensure that the pseudo node range is updated to reflect the whole span of the children also when it is created. The range was previously only extended after the _third_ child is seen, pseudo nodes with only two children always were stuck with the range of the first one. This caused issues when pseudo node ranges are used to derive overlapping clusters, like #985.
Fixes #985 by ensuring that the sortable clusters are calculated correctly by fixing pseudo-node range derivation.

Ensure pseudo feature node range is updated

---

INSTALL
README
README.md

Watching some issues being reported that seem to be caused by a misunderstanding of how to install GenomeTools (most likely after googling), I propose a slight update of the `README` and `INSTALL` files.
- Clarify supported Debian and Ubuntu versions for `apt` installation. GenomeTools has been in stable for years now.
- Add Homebrew install instructions for Mac users.
- Switch to current "macOS" name instead of "Mac OS X".
- Remove Gitter reference (or does anyone still watch that?)
- Note in `README` in what cases building from source is required.
- Remove reference to universal binaries from `INSTALL` as that should be only of historic value and may confuse readers.
- Mention `gtgo/` in `README`.
- Update Homebrew dependency list to what is …

Update README.* and INSTALL

---

src/extended/gff3_parser.c

- Make sure that roots are only slated for joining via pseudo node once. This fixes a bug surfacing when a child feature has multiple paths to its root.
Fixes #990

deduplicate roots before joining

---

src/extended/gff3_linesorted_out_stream.c
src/match/dbs_spaced_seeds.c
src/match/eis-bwtseq-extinfo.c
src/match/encseq2offset.c
src/match/firstcodes.c
src/match/ft-front-generation.c
src/match/randomcodes-sfx-partssuf.c
src/match/randomcodes.c
src/match/sfx-lcpvalues.c
src/match/sfx-partssuf.c
testsuite/gt_gff3_include.rb

- Change the behaviour of `gt gff3 -sortlines` to only flush sorted lines at the end of each sequence boundary. We can not only look at transitively overlapping clusters because features at the end of the sequence may have children at the beginning of the sequence, and if we flush before we are breaking sortedness.
- Annotate unused variables from old debug code to fix build.
Fixes #1001

implement less efficient but correct -sortlines

---

src/extended/gff3_parser.c
testdata/forward_wrong_seqid.gff3
testsuite/gt_gff3_include.rb

- Ensure that checks for required preconditions that might cause assertions to fail are also done for orphan nodes (i.e. nodes with forward references to yet unseen parent nodes). This has been shown to open a different code path in which some of these tests can be skipped, leading to issues later.
Fixes #851.

ensure validity checks for orphan nodes

---

src/core/qsort_r.c
src/extended/region_mapping.c
src/ltr/ltrdigest_pbs_visitor.c
src/ltr/ltrdigest_ppt_visitor.c

- Switch two variables in `core/qsort_r.c` to `long` from `int` to counter overflows when processing large data, as reported by LTRharvest users.
- Initalize some variables to fix building on macOS with gcc.
Adresses #940 by including a patch proven to solve the issue for at least one user. I can not see significantly bad side effects at first glance.

fix quicksort segfault

---

gtpython/gt/annotationsketch/diagram.py
gtpython/gt/annotationsketch/graphics.py
gtpython/gt/annotationsketch/style.py
gtpython/gt/bytes.py
gtpython/gt/core/alphabet.py
gtpython/gt/core/encseq.py
gtpython/gt/core/error.py
gtpython/gt/core/gtstr.py
gtpython/gt/core/str_array.py
gtpython/gt/extended/comment_node.py
gtpython/gt/extended/dup_feature_stream.py
gtpython/gt/extended/feature_index.py
gtpython/gt/extended/feature_node.py
gtpython/gt/extended/gff3_in_stream.py
gtpython/gt/extended/inter_feature_stream.py
gtpython/gt/extended/meta_node.py
gtpython/gt/extended/sequence_node.py
testdata/gtpython/style.py
testdata/gtpython/unicode_strings.py
testsuite/gt_python_include.rb

This commit unifies string and bytes passing to ctypes across Python 2 and Python 3 situations.
- New Python library function `gt.bytes.gtbytes()` that converts any value to its string representation as a bytes buffer to be passed to ctypes `c_char_p` type parameters. This allows the code to be run on Python 2 and 3 without changes.
- Switch previous `encode('utf-8')` calls and any raw string passes to the new unified function.

unify Python bytes/string handling

---

src/gtlua/genome_node_lua.c
testdata/gtscripts/genome_node.lua

- Check in the Lua bindings whether the leaf to remove via `genome_node:remove_leaf()` is actually a leaf. If not, a runtime error is raised instead of triggering an assertion in the underlying C function.
Addresses #1020 by avoiding a hard assertion failure.

gtlua: check for leaf property in `remove_leaf()`

---

.github/workflows/build.yaml
.github/workflows/release.yaml
Makefile

- Adds GitHub-based release workflow that creates a release and builds and uploads binary 
distributions as attachments to it, whenever a new version tag (`'v*'`)is pushed.
It builds Linux, macOS (both with or without Cairo support, as amalgamations) as well as
cross-compiled Windows binaries (without Cairo).
- Adjust `Makefile` to enable successful completion of some of the distribution builds 
(mostly Windows).

Add GitHub-based release workflow

---

.github/workflows/build.yaml
Makefile

- change `errorcheck` (enabling `-Werror`) to opt-in, i.e. not set by default.
- adapt CI to still use it
Adresses #1024 by implementing OP's request.

make `errorcheck`/`-Werror` optional

---

scripts/ctags.sh
src/core/encseq.c
src/core/md5_tab.c
src/extended/editscript.c
src/ltr/ltrdigest_pdom_visitor.c
src/ltr/ltrharvest_stream.c
src/match/cgr_spacedseed.c
src/match/chain2dim.c
src/match/dbs_spaced_seeds.c
src/match/ft-front-generation.c
src/match/rdj-spmfind.c
src/match/sfx-mapped4.gen

1) src/core/md5_tab.c
init len = 0, as len may not be defined when first used
2) src/core/encseq.c
if sat is undefined out sat and not gt_encseq_access_type_str(sat)
Remove src/gth/*.[ch] list of paths expressions in ctags.sh
- ...
- ...
- ...
Fixes #...
Adresses #... by ...

Fixed lines resulting in compiler errors for gcc-13-2

---

gtpython/gt/extended/__init__.py
gtpython/gt/extended/gff3_in_stream.py
gtpython/gt/extended/type_checker.py
gtpython/tests/__init__.py
gtpython/tests/test_stream.py
gtpython/tests/test_typechecker.py
testdata/unknowntype.gff3

- Add Python bindings for the `TypeChecker`, `TypeCheckerBuiltin` and `TypeCheckerOBO` classes.
- Add Python bindings for `gt_gff3_in_stream_enable_tidy_mode()`, `gt_gff3_in_stream_check_id_attributes()` and `gt_gff3_in_stream_enable_strict_mode()`
- Add tests for new features.
These are required to implement the GFF3 web validator using the more future-proof Python bindings, to replace the old version based on the Ruby bindings which are tied to the obsolete Ruby 1.8.

Add Python bindings required for GFF3 web validator
