genometools/genometools

- src/core/bittab_api.h
- www/genometools.org/htdocs/docs.html
- www/genometools.org/htdocs/libgenometools.html
Just fixing the code layout....
> Bittab: coding style

- www/genometools.org/htdocs/cgi-bin/gff3validator.cgi
Already installed and tested, see http://genometools.org/cgi-bin/gff3validator.cgi
> gff3 online validator: allow to disable SO

- CHANGELOG
- src/extended/gff3_parser.c
- testdata/multi_feature_orphan.gff3
- testsuite/gt_gff3_include.rb
Multiple improvements to the GFF3 parser to make it more robust and improve the user experience of the GFF3 validator.
> gff3 parser: multiple improvements

- src/annotationsketch/diagram.c
- src/core/accspecialrange.gen
- src/core/encseq.c
- src/extended/sequence_node_add_stream.c
This PR addresses several minor memory-based issues as well as #527.
> Small fixes

- src/extended/hcr.c
- src/extended/hcr.h
- src/tools/gt_compreads_decompress.c
bug #539 is still unfixed and will have to wait until I have time for it.
> Compreads smaller issue fixes

- scripts/DW-pre-commit
- src/core/alphabet.c
- src/core/alphabet_api.h
- src/core/radix_sort.h
- src/core/seq_iterator_sequence_buffer_api.h
- src/core/sequence_buffer_fasta.c
- src/core/str_array.h
- src/extended/blast_process_call.c
- src/extended/blast_process_call.h
- src/extended/match_api.h
- src/extended/match_iterator_blast.c
- src/tools/gt_encseq_decode.c
this includes extending documentation, including a function in its header to
access it, and a small fix to blastp call creation
> a collection of small fixes and cosmetic changes

- INSTALL
This PR changes the INSTALL file to no longer mention obsolete build instructions.
> update INSTALL file

- Makefile
- src/core/versionfunc.c
- src/gth/run_header.c
> remove GT_BUILT to make builds reproducible

- src/gth/parse_options.c
- src/tools/gt_hop.c
> fix possible error in errmsg and usage of \% to %% in formatstring

- CHANGELOG
- src/extended/inter_feature_visitor.c
- testdata/interfeat_pseudo.gff3
- testdata/interfeat_pseudo.out
- testsuite/gt_interfeat_include.rb
> `gt interfeat` handles top-level multi-features

- src/core/file.c
- src/core/file_api.h
- src/extended/gff3_visitor.c
- src/gtlua/genome_stream_lua.c
- src/gtlua/genome_stream_lua.h
- testdata/genome_stream_stdin.gff3
- testdata/gtscripts/genome_stream_outfile.lua
- testdata/gtscripts/genome_stream_stdin.lua
- testsuite/gt_scripts_include.rb
> Extend Lua stream functionality

- CHANGELOG
- src/core/assert_api.h
- www/genometools.org/htdocs/docs.html
- www/genometools.org/htdocs/libgenometools.html
> gt_assert() calls abort(3) instead of exit(3)

- scripts/DW-pre-commit
- src/core/encseq.h
- src/core/fasta_api.h
- src/core/io.h
- src/core/splitter.c
- src/core/splitter_api.h
- src/core/str.h
- src/core/tokenizer.c
- src/extended/condenseq.c
- src/extended/condenseq.h
- src/extended/condenseq_rep.h
- src/extended/condenseq_search_arguments.c
- src/extended/condenseq_search_arguments.h
- src/extended/encdesc.c
- src/extended/rbtree.h
- src/ltr/ltrdigest_pdom_visitor.c
- src/tools/gt_condenseq.c
- src/tools/gt_condenseq_blast.c
- src/tools/gt_condenseq_hmmsearch.c
- src/tools/gt_condenseq_hmmsearch.h
- src/tools/gt_condenseq_search.c
this adds a new subtool to the condenseq search toolbox
> Condenseq hmmer search

- src/extended/dup_feature_visitor.c
> bug fix: remove unnecessary check

- src/core/bioseq.c
> do not use static 'stdin' name for stdin Bioseqs

- src/tools/gt_seqstat.c
> make -contigs the default for gt seqstat

- gtdata/modules/optparse.lua
- src/gtr.c
Implements a git-like behaviour as proposed in #616.
> search $PATH for user scripts

- src/core/gtdatapath.c
> be a bit more defensive looking for gtdata directory

- src/tools/gt_seqorder.c
> improve -help output of `gt seqorder`

- src/gtlua/genome_node_lua.c
- testdata/gtscripts/genome_node.lua
> gtlua: fix bug in feature_node:add_child()

- src/match/seed-extend.c
check pointer parameter of API-function for NULL
> small scan-build fix

- CHANGELOG
- scripts/Vagrantfile
- src/gth/dp_param.c
This PR does the following:
- fix compilation on Mac OS X 10.11 El Capitan (@gordon, this touches your code)
- update CHANGELOG
- add a Vagrantfile in `scripts/` defining an environment for running `scripts/build_dists.sh` including all dependencies
> prepare for release

- testsuite/gt_condenseq_include.rb
remove long running tests as they do not add anything valuable to the tests.
> remove large test

- scripts/Vagrantfile
- src/core/fa.c
- src/ltr/ltrdigest_pdom_visitor.c
This PR addresses #681 and #599.
> bug fix and error reporting improvement

- src/extended/gff3_parser.c
- testdata/revision_numbers.gff3
- testdata/revision_numbers.out
- testsuite/gt_gff3_include.rb
- Some code improvements.
- Add a test that checks we can process the new 3.2.1 version numbers without an error.
> improve parsing of gff-version line

- .travis.yml
- src/core/types_api.h
- src/ltr/ltrdigest_pdom_visitor.c
- src/match/diagbandseed.c
- src/match/diagbandseed.h
> Allow compilation for Windows.

- src/ltr/ltrdigest_file_out_stream.c
This PR changes the behaviour of LTRdigest not to keep open up to two files per pHMM domain hit (if `-outfileprefix`, `-aaout` and `-aliout` is used) which makes the tool in general more economic w.r.t. open file descriptors, decreasing the likelihood of problems like #681 occurring. Closes #681.
> do not keep open 1-2 files per domain hit

- src/tools/gt_gff3.c
> improve documentation of `gt gff3 -checkids`

- src/extended/priority_queue.c
Please read the two commit messages.
> Two small changes to the priority queue. 

- src/extended/priority_queue.c
checks the cases in #714, also removes `exit` calls to bring the test in line with the rest of the GenomeTools style
> update unit test for GtPriorityQueue

- src/extended/gff3_linesorted_out_stream.c
- src/extended/gff3_linesorted_out_stream.h
- testdata/linesort_test_1.gff3
- testdata/linesort_test_1.out
- testdata/linesort_test_2.gff3
- testdata/linesort_test_2.out
- testdata/linesort_test_3.gff3
- testdata/linesort_test_3.out
- testsuite/gt_gff3_include.rb
Fixes #716 by implementing more strict parsing.
> Fix line sorting bug

- src/core/encseq_col.c
When looking at another issue I noticed this potential issue where a sequence description is copied to a fixed size buffer in an unsafe manner.
> avoid dangerous string handling

- src/match/eis-encidxseq.c
- src/tools/gt_compreads_decompress.c
- src/tools/gt_kmer_database.c
> fix minor spelling issues

- doc/devguide/devguide.tex
This PR updates the developer's guide to include new make options and a new contact email address.
> update developers guide

- src/match/diagbandseed.c
- src/match/diagbandseed.h
- src/match/querymatch.c
- src/match/querymatch.h
- src/tools/gt_seed_extend.c
- testsuite/gt_seed_extend_include.rb
also fixed an issue with sequences that consist of wild-cards only
> Choose part of GtEncseq for seed extension

- src/extended/affinealign.h
- src/extended/type_node.c
- src/gth/align_protein.c
- src/tools/gt_condenseq_compress.c
- src/tools/gt_linspace_align.c
Some more spelling issues reported by Lintian.
> spelling issues

- gtscripts/gtdoc.lua
this allows to create api-documents for regular header files
> change doc-creation if option -f is given.

- src/extended/cds_check_visitor.c
- testdata/gt_gff3_phases4.gff3
- testdata/gt_gff3_phases5.gff3
- testdata/gt_gff3_phases6.gff3
- testdata/gt_gff3_phases7.gff3
- testsuite/gt_gff3_include.rb
- address corner case where first CDS in transcript is shorter than phase skip 
Adresses #793.
> address corner case

- doc/devguide/devguide.tex
- add date to developers guide LaTeX source; required for reproducible documentation building
> add date to developers guide

- testdata/gt_sketch_textwidth.gff3
- Adjust text used in test case 1381 to be less likely to hit font variation problems on different systems.
Fixes #837.
> change test caption to be less problematic

- src/extended/intset.h
- src/tools/gt_kmer_database.c
This PR fixes some typos in help output and comments. Fixed in Debian package to silence Lintian.
> fix spelling issues

- testsuite/gt_linspace_align_include.rb
increased test maxtime to fix issue described in #834 for gt_linspace_align
Adresses #834
> added increased maxtime

- src/ltr/pdom_model_set.c
This PR breaks up a long line.
one could discuss to extend our limit to 100 characters.
> line >80 characters

- src/gth/bssm_seq_processor.c
- src/gth/bssm_seq_processor.h
- src/gth/gt_gthbssmtrain.c
Possibly due to wrong -extracttype option.
> gthbssmtrain: give an error if no sites were found

- CONTRIBUTORS
updates the list of contributions.
> add contributions

- INSTALL
- Addition of further information on required dependencies to ease building on new distributions.
Adresses #898.
> elaborate on dependencies in INSTALL

- src/tools/gt_linspace_align.c
- Fix spelling issue as detected by Debian tooling.
> fix spelling

- src/ltr/ltrdigest_file_out_stream.c
- src/mgth/metagenomethreader.h
- Establish successful build process with GCC 10 by addressing some new checks and/or characteristics that caused the build to fail. See commit messages for more details.
Fixes #941.
> Enable building on GCC 10

- Makefile
- go.mod
- gtgo/cmd/gff3validator_go/gff2validator_go.go
- gtgo/error.go
- gtgo/genome_node.go
- gtgo/genometools.go
- gtgo/gff3_in_stream.go
- gtgo/node_stream.go
The two CGI scripts based on ruby1.8 in cgi-bin need to be replaced.
The is the first step of a Go rewrite.
> Go bindings for libgenometools proof-of-concept

- gtpython/gt/extended/feature_node.py
- gtpython/tests/__init__.py
- gtpython/tests/test_featurenode.py
- Change back module handling to previous configuration.
- Do not reuse finished iterator in tests.
- Ensure we pass the correct pointers into C functions.
- Use correct test condition.
Sorry this slipped through, good to have CI back!
> fix gtpython tests

- CHANGELOG
- gtpython/gt/core/gtrange.py
- gtpython/gt/extended/feature_node.py
- gtpython/gt/extended/genome_node.py
Let's get this into the next release as well.
- Add Python `feature_node.set_attribute()` and `genome_node.set_range()`.
Closes #978.
> Last-minute Python API additions `feature_node.set_attribute()` and `genome_node.set_range()`

- src/ltr/ltrdigest_pdom_visitor.c
- Ensure `gt_ltrdigest_pdom_visitor_choose_strand()` is not called in cases where the input does not contain an `LTR_retrotransposon` feature. This would cause a failed assertion otherwise.
Fixes #982
> fix error handling flow

- README.md
Removed prompt characters that make it impossible to copy+paste README instructions
> Sorry to bother, this just is one of those things that irks me
